---
- name: Install Jenkins
  hosts: managers[0]
  vars:
    jenkins_install_via: "docker"
    jenkins_config_owner: "vagrant"
    jenkins_config_group: "vagrant"
    jenkins_port: "10080" 
    jenkins_plugins:
      - git
  roles:
    - emmetog.jenkins
  become: yes
  become_user: root
  become_method: sudo

        # - docker_users: ["docker", "vagrant"]
    # - jenkins_port: 10080