---
- name: Remove worker from swarm cluster
  hosts: worker2
  roles:
    - docker-swarm-remove
- name: Remove worker or manager from manager swarm cluster
  hosts: managers
  roles:
  - { role: docker-swarm-delete, host: 'worker2' }

# - name: Remove manager from swarm cluster
#   hosts: managers
#   roles:
#     - docker-swarm-remove