version: "3.2"

services:

  # elasticsearch:
  #   command: elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch
  #   environment:
  #     ES_JAVA_OPTS: -Xms1g -Xmx1g
  #   image: elasticsearch:5
  #   ulimits:
  #     memlock: -1
  #     nofile:
  #       hard: 65536
  #       soft: 65536
  #     nproc: 65538
  #   volumes:
  #     - /usr/share/elasticsearch/data
  #   networks:
  #     - elk
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     endpoint_mode: dnsrr
  # kibana:
  #   image: kibana:latest
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #   networks:
  #     - elk
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   healthcheck:
  #     test: wget -qO- http://localhost:5601 > /dev/null
  #     interval: 30s
  #     retries: 3
  logstash:
    image: ahromis/logstash:5.5.1-alpine
    hostname: logstash
    networks:
      - elk
    deploy:
      mode: global
    volumes:
      - logbook_docker-journal:/log/docker
      - logstash-sincedb:/usr/share/logstash/data
      - /var/lib/docker/volumes:/log/volumes

volumes:
  logstash-sincedb:
    driver: local
  logbook_docker-journal:
    external: true

networks:
  elk:
    driver: overlay
    driver_opts:
      encrypted: "true"
