---
- name: Copy Public key to Other hosts
  become: true
  become_user: vagrant
  copy:
    src: /tmp/id_rsa.pub
    dest: /tmp/id_rsa.pub
    mode: 0644
- name: Append public key in authorized_keys file
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"