
- name: Start registrator globally and connect to consul cluster
  shell: >
    docker service create \
      --name registrator \
      --mount type=bind,target=/tmp/docker.sock,src=/var/run/docker.sock \
      --network appnet \
      --mode global \
      gliderlabs/registrator:latest \
      consul://{{ hostvars[inventory_hostname]['ansible_docker0']['ipv4']['address'] }}:8500
  tags:
    - registrator
  become: yes
  become_user: root