---
- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -f /home/vagrant/.ssh/id_rsa -t rsa -q -N ""
  args:
    creates: /home/vagrant/.ssh/id_rsa
- name: Copy Public key locally
  fetch:
    src: /home/vagrant/.ssh/id_rsa.pub
    dest: /tmp/
    flat: yes
- name: Copy SSH Configuration
  copy:
    src: ssh_config
    dest: /home/vagrant/.ssh/config
    mode: 0644
- name: empty known_hosts
  file: 
    state: absent
    path: ~/.ssh/known_hosts
- name: run ssh-keyscan to add to known_hosts
  shell: "ssh-keyscan {{ item }} >> ~/.ssh/known_hosts"
  with_items:
    - "manager1"
    - "worker1"
    - "worker2"