---
- name: Install epel
  yum: name=epel-release state=latest
  ignore_errors: yes
  become: yes
  become_user: root
  become_method: sudo
  
- name: Install Dependencies from yum
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python-pip
  tags: docker
  ignore_errors: yes
  become: yes
  become_user: root
  become_method: sudo
- name: Remove docker-py
  command: pip uninstall docker-py && pip uninstall docker-compose 
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: true

- name: Install Dependencies from pip
  pip: name={{ item }} state=latest
  with_items:
    - docker-compose
    - jsondiff
  become: yes
  become_user: root
  become_method: sudo