---  
- name: Add Worker to the swarm cluster
  shell: "docker swarm join --token {{ hostvars[item]['worker_token']['stdout'] }} {{item}}:2377"
  ignore_errors: true
  tags: swarm
  with_items:
    - "{{ groups['managers'][0] }}"